//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientCalculator.CalculatorServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ComplexNumber", Namespace="http://schemas.datacontract.org/2004/07/wcf_calc_demo")]
    [System.SerializableAttribute()]
    public partial class ComplexNumber : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ImaginaryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double RealField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Imaginary {
            get {
                return this.ImaginaryField;
            }
            set {
                if ((this.ImaginaryField.Equals(value) != true)) {
                    this.ImaginaryField = value;
                    this.RaisePropertyChanged("Imaginary");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Real {
            get {
                return this.RealField;
            }
            set {
                if ((this.RealField.Equals(value) != true)) {
                    this.RealField = value;
                    this.RaisePropertyChanged("Real");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculatorServiceReference.ICalculator")]
    public interface ICalculator {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiply", ReplyAction="http://tempuri.org/ICalculator/MultiplyResponse")]
        ClientCalculator.CalculatorServiceReference.ComplexNumber Multiply(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Multiply", ReplyAction="http://tempuri.org/ICalculator/MultiplyResponse")]
        System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> MultiplyAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Substract", ReplyAction="http://tempuri.org/ICalculator/SubstractResponse")]
        ClientCalculator.CalculatorServiceReference.ComplexNumber Substract(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Substract", ReplyAction="http://tempuri.org/ICalculator/SubstractResponse")]
        System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> SubstractAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Add", ReplyAction="http://tempuri.org/ICalculator/AddResponse")]
        ClientCalculator.CalculatorServiceReference.ComplexNumber Add(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Add", ReplyAction="http://tempuri.org/ICalculator/AddResponse")]
        System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> AddAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Divade", ReplyAction="http://tempuri.org/ICalculator/DivadeResponse")]
        ClientCalculator.CalculatorServiceReference.ComplexNumber Divade(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculator/Divade", ReplyAction="http://tempuri.org/ICalculator/DivadeResponse")]
        System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> DivadeAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculatorChannel : ClientCalculator.CalculatorServiceReference.ICalculator, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculatorClient : System.ServiceModel.ClientBase<ClientCalculator.CalculatorServiceReference.ICalculator>, ClientCalculator.CalculatorServiceReference.ICalculator {
        
        public CalculatorClient() {
        }
        
        public CalculatorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculatorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculatorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public ClientCalculator.CalculatorServiceReference.ComplexNumber Multiply(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.Multiply(complexNumber, complexNumber_2, complex);
        }
        
        public System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> MultiplyAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.MultiplyAsync(complexNumber, complexNumber_2, complex);
        }
        
        public ClientCalculator.CalculatorServiceReference.ComplexNumber Substract(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.Substract(complexNumber, complexNumber_2, complex);
        }
        
        public System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> SubstractAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.SubstractAsync(complexNumber, complexNumber_2, complex);
        }
        
        public ClientCalculator.CalculatorServiceReference.ComplexNumber Add(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.Add(complexNumber, complexNumber_2, complex);
        }
        
        public System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> AddAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.AddAsync(complexNumber, complexNumber_2, complex);
        }
        
        public ClientCalculator.CalculatorServiceReference.ComplexNumber Divade(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.Divade(complexNumber, complexNumber_2, complex);
        }
        
        public System.Threading.Tasks.Task<ClientCalculator.CalculatorServiceReference.ComplexNumber> DivadeAsync(ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber, ClientCalculator.CalculatorServiceReference.ComplexNumber complexNumber_2, string complex) {
            return base.Channel.DivadeAsync(complexNumber, complexNumber_2, complex);
        }
    }
}
